### ISSUE TITLE
This was used by malware.

### ISSUE THREAD

**Issue by Tamschi** [charlyBerthet/bypasscors#1]
Hi,

I just wanted to let you know your service was used to enable anonymous backdoor hosting, in case Heroku's notification is too unspecific.  
Please see [Discord Turned Into an Info-Stealing Backdoor by New Malware](https://www.bleepingcomputer.com/news/security/discord-turned-into-an-info-stealing-backdoor-by-new-malware/) for details.

I hope you understand why unrestricted bypass services like this one mustn't exist and that there will be no ill will regarding it going offline.

**Comment by charlyBerthet** [comment]
Ohhhhh, Sorry for that... Thanks for reporting
